version: "3.8"

services:
  doc-manager-db:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: docmanager
      POSTGRES_PASSWORD: postgres
    volumes:
      - doc-manager-db-vol:/var/lib/postgresql/data

volumes:
  doc-manager-db-vol:
